// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pancake_Final.Data;

#nullable disable

namespace Pancake_Final.Migrations
{
    [DbContext(typeof(Pancake_FinalContext))]
    [Migration("20250211185132_testuser")]
    partial class testuser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ad2bcf0c-20db-474f-8407-5a6b159518ba",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "bd2bcf0c-20db-474f-8407-5a6b159518bb",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            RoleId = "ad2bcf0c-20db-474f-8407-5a6b159518ba"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Pancake_Final.Data.Pancake_FinalUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "69604e33-0ae8-4786-8dee-19a5ada906f7",
                            Email = "admin@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECOoAwTaCAW4xeIHk3oqhTYtbM9iFU9g9mn1qd5o7lqJlyaTh8fE3kx1h05mH0sD5Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e2551112-1529-4878-b35d-0a5c52c3aa65",
                            SubStatus = "Premium",
                            TwoFactorEnabled = false,
                            UserName = "admin@localhost.com"
                        });
                });

            modelBuilder.Entity("Pancake_Final.Domain.Album", b =>
                {
                    b.Property<int>("AlbumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlbumID"));

                    b.Property<byte>("AlbumImage")
                        .HasColumnType("tinyint");

                    b.Property<int>("ArtistID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("GenID")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AlbumID");

                    b.ToTable("Album");
                });

            modelBuilder.Entity("Pancake_Final.Domain.Artists", b =>
                {
                    b.Property<int>("ArtistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtistID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.HasKey("ArtistID");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("Pancake_Final.Domain.Genre", b =>
                {
                    b.Property<int>("GenreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreID"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("GenreName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreID");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            GenreID = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 11, 18, 51, 30, 759, DateTimeKind.Utc).AddTicks(598),
                            DateUpdated = new DateTime(2025, 2, 11, 18, 51, 30, 759, DateTimeKind.Utc).AddTicks(599),
                            GenreName = "Liked Songs",
                            Id = 1,
                            UpdateBy = "System"
                        });
                });

            modelBuilder.Entity("Pancake_Final.Domain.ListeningHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatePlayed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SongId")
                        .HasColumnType("int");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("HistoryId");

                    b.ToTable("ListeningHistory");
                });

            modelBuilder.Entity("Pancake_Final.Domain.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PayId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethod");
                });

            modelBuilder.Entity("Pancake_Final.Domain.Playlist", b =>
                {
                    b.Property<int>("PlaylistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlaylistId"));

                    b.Property<string>("CoverImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("GenreID")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("NewGenreName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaylistName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PlaylistId");

                    b.HasIndex("GenreID");

                    b.ToTable("Playlist");
                });

            modelBuilder.Entity("Pancake_Final.Domain.Song", b =>
                {
                    b.Property<int?>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("SongId"));

                    b.Property<int?>("AlbumID")
                        .HasColumnType("int");

                    b.Property<int?>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int?>("ArtistsArtistID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GenID")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("LikedS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlaylistId")
                        .HasColumnType("int");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SongId");

                    b.HasIndex("ArtistsArtistID");

                    b.HasIndex("PlaylistId");

                    b.ToTable("Song");

                    b.HasData(
                        new
                        {
                            SongId = 1,
                            ArtistId = 1,
                            CreatedBy = "Seeder",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2025, 2, 12, 2, 51, 30, 751, DateTimeKind.Local).AddTicks(1778),
                            DateUpdated = new DateTime(2025, 2, 12, 2, 51, 30, 751, DateTimeKind.Local).AddTicks(1793),
                            Duration = new TimeSpan(1877739166),
                            FilePath = "/music/Don Toliver - No Pole.mp3",
                            GenID = 1,
                            Id = 0,
                            LikedS = "NotLiked",
                            Name = "Don Toliver - No Pole",
                            UpdateBy = "Seeder"
                        },
                        new
                        {
                            SongId = 2,
                            ArtistId = 1,
                            CreatedBy = "Seeder",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2025, 2, 12, 2, 51, 30, 751, DateTimeKind.Local).AddTicks(5441),
                            DateUpdated = new DateTime(2025, 2, 12, 2, 51, 30, 751, DateTimeKind.Local).AddTicks(5447),
                            Duration = new TimeSpan(1297645833),
                            FilePath = "/music/Genshin Impact丨Zhongli Theme musicListenerOST原神钟离听书人.mp3",
                            GenID = 1,
                            Id = 0,
                            LikedS = "NotLiked",
                            Name = "Genshin Impact丨Zhongli Theme musicListenerOST原神钟离听书人",
                            UpdateBy = "Seeder"
                        },
                        new
                        {
                            SongId = 3,
                            ArtistId = 1,
                            CreatedBy = "Seeder",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2025, 2, 12, 2, 51, 30, 751, DateTimeKind.Local).AddTicks(9156),
                            DateUpdated = new DateTime(2025, 2, 12, 2, 51, 30, 751, DateTimeKind.Local).AddTicks(9161),
                            Duration = new TimeSpan(2111185000),
                            FilePath = "/music/Goblin Slayer - Rightfully _ Mili [Full].mp3",
                            GenID = 1,
                            Id = 0,
                            LikedS = "NotLiked",
                            Name = "Goblin Slayer - Rightfully _ Mili [Full]",
                            UpdateBy = "Seeder"
                        },
                        new
                        {
                            SongId = 4,
                            ArtistId = 1,
                            CreatedBy = "Seeder",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2025, 2, 12, 2, 51, 30, 752, DateTimeKind.Local).AddTicks(7096),
                            DateUpdated = new DateTime(2025, 2, 12, 2, 51, 30, 752, DateTimeKind.Local).AddTicks(7105),
                            Duration = new TimeSpan(1873305000),
                            FilePath = "/music/Goblins from Mars  - Put Your Love In Dreamz.mp3",
                            GenID = 1,
                            Id = 0,
                            LikedS = "NotLiked",
                            Name = "Goblins from Mars  - Put Your Love In Dreamz",
                            UpdateBy = "Seeder"
                        },
                        new
                        {
                            SongId = 5,
                            ArtistId = 1,
                            CreatedBy = "Seeder",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2025, 2, 12, 2, 51, 30, 753, DateTimeKind.Local).AddTicks(3907),
                            DateUpdated = new DateTime(2025, 2, 12, 2, 51, 30, 753, DateTimeKind.Local).AddTicks(3913),
                            Duration = new TimeSpan(1812530833),
                            FilePath = "/music/Goblins from Mars - Cold Blooded Love (ft. Krista Marina).mp3",
                            GenID = 1,
                            Id = 0,
                            LikedS = "NotLiked",
                            Name = "Goblins from Mars - Cold Blooded Love (ft. Krista Marina)",
                            UpdateBy = "Seeder"
                        },
                        new
                        {
                            SongId = 6,
                            ArtistId = 1,
                            CreatedBy = "Seeder",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2025, 2, 12, 2, 51, 30, 753, DateTimeKind.Local).AddTicks(9625),
                            DateUpdated = new DateTime(2025, 2, 12, 2, 51, 30, 753, DateTimeKind.Local).AddTicks(9631),
                            Duration = new TimeSpan(2091100833),
                            FilePath = "/music/Goblins from Mars - Heart Afire When The Bassjumps.mp3",
                            GenID = 1,
                            Id = 0,
                            LikedS = "NotLiked",
                            Name = "Goblins from Mars - Heart Afire When The Bassjumps",
                            UpdateBy = "Seeder"
                        },
                        new
                        {
                            SongId = 7,
                            ArtistId = 1,
                            CreatedBy = "Seeder",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2025, 2, 12, 2, 51, 30, 754, DateTimeKind.Local).AddTicks(3031),
                            DateUpdated = new DateTime(2025, 2, 12, 2, 51, 30, 754, DateTimeKind.Local).AddTicks(3035),
                            Duration = new TimeSpan(2760920833),
                            FilePath = "/music/Gotoubun no Hanayome Ending Full SignCandy Flavor - Aya Uchida Lyrics [CC].mp3",
                            GenID = 1,
                            Id = 0,
                            LikedS = "NotLiked",
                            Name = "Gotoubun no Hanayome Ending Full SignCandy Flavor - Aya Uchida Lyrics [CC]",
                            UpdateBy = "Seeder"
                        },
                        new
                        {
                            SongId = 8,
                            ArtistId = 1,
                            CreatedBy = "Seeder",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2025, 2, 12, 2, 51, 30, 754, DateTimeKind.Local).AddTicks(7124),
                            DateUpdated = new DateTime(2025, 2, 12, 2, 51, 30, 754, DateTimeKind.Local).AddTicks(7129),
                            Duration = new TimeSpan(2822477500),
                            FilePath = "/music/Grancrest Senki Opening 2 Full _ Rin - ASCA Lyrics [CC].mp3",
                            GenID = 1,
                            Id = 0,
                            LikedS = "NotLiked",
                            Name = "Grancrest Senki Opening 2 Full _ Rin - ASCA Lyrics [CC]",
                            UpdateBy = "Seeder"
                        },
                        new
                        {
                            SongId = 9,
                            ArtistId = 1,
                            CreatedBy = "Seeder",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2025, 2, 12, 2, 51, 30, 755, DateTimeKind.Local).AddTicks(2925),
                            DateUpdated = new DateTime(2025, 2, 12, 2, 51, 30, 755, DateTimeKind.Local).AddTicks(2931),
                            Duration = new TimeSpan(2235863333),
                            FilePath = "/music/grandson - Despicable.mp3",
                            GenID = 1,
                            Id = 0,
                            LikedS = "NotLiked",
                            Name = "grandson - Despicable",
                            UpdateBy = "Seeder"
                        },
                        new
                        {
                            SongId = 10,
                            ArtistId = 1,
                            CreatedBy = "Seeder",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2025, 2, 12, 2, 51, 30, 755, DateTimeKind.Local).AddTicks(6815),
                            DateUpdated = new DateTime(2025, 2, 12, 2, 51, 30, 755, DateTimeKind.Local).AddTicks(6820),
                            Duration = new TimeSpan(1464057500),
                            FilePath = "/music/Greatest Battle Music Of All Times Saijaku Muhai.mp3",
                            GenID = 1,
                            Id = 0,
                            LikedS = "NotLiked",
                            Name = "Greatest Battle Music Of All Times Saijaku Muhai",
                            UpdateBy = "Seeder"
                        },
                        new
                        {
                            SongId = 11,
                            ArtistId = 1,
                            CreatedBy = "Seeder",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2025, 2, 12, 2, 51, 30, 755, DateTimeKind.Local).AddTicks(9973),
                            DateUpdated = new DateTime(2025, 2, 12, 2, 51, 30, 755, DateTimeKind.Local).AddTicks(9978),
                            Duration = new TimeSpan(916307500),
                            FilePath = "/music/Gundam - OP1 HD.mp3",
                            GenID = 1,
                            Id = 0,
                            LikedS = "NotLiked",
                            Name = "Gundam - OP1 HD",
                            UpdateBy = "Seeder"
                        },
                        new
                        {
                            SongId = 12,
                            ArtistId = 1,
                            CreatedBy = "Seeder",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2025, 2, 12, 2, 51, 30, 756, DateTimeKind.Local).AddTicks(2828),
                            DateUpdated = new DateTime(2025, 2, 12, 2, 51, 30, 756, DateTimeKind.Local).AddTicks(2833),
                            Duration = new TimeSpan(0, 0, 3, 57, 567),
                            FilePath = "/music/Gundam - Seed.mp3",
                            GenID = 1,
                            Id = 0,
                            LikedS = "NotLiked",
                            Name = "Gundam - Seed",
                            UpdateBy = "Seeder"
                        },
                        new
                        {
                            SongId = 13,
                            ArtistId = 1,
                            CreatedBy = "Seeder",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2025, 2, 12, 2, 51, 30, 756, DateTimeKind.Local).AddTicks(5282),
                            DateUpdated = new DateTime(2025, 2, 12, 2, 51, 30, 756, DateTimeKind.Local).AddTicks(5287),
                            Duration = new TimeSpan(2539995000),
                            FilePath = "/music/Hans Zimmer - Flight.mp3",
                            GenID = 1,
                            Id = 0,
                            LikedS = "NotLiked",
                            Name = "Hans Zimmer - Flight",
                            UpdateBy = "Seeder"
                        },
                        new
                        {
                            SongId = 14,
                            ArtistId = 1,
                            CreatedBy = "Seeder",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2025, 2, 12, 2, 51, 30, 756, DateTimeKind.Local).AddTicks(7829),
                            DateUpdated = new DateTime(2025, 2, 12, 2, 51, 30, 756, DateTimeKind.Local).AddTicks(7834),
                            Duration = new TimeSpan(5451416666),
                            FilePath = "/music/Hiroyuki Sawano ashes Suite [vocal gemie] Epic Battle Music.mp3",
                            GenID = 1,
                            Id = 0,
                            LikedS = "NotLiked",
                            Name = "Hiroyuki Sawano ashes Suite [vocal gemie] Epic Battle Music",
                            UpdateBy = "Seeder"
                        },
                        new
                        {
                            SongId = 15,
                            ArtistId = 1,
                            CreatedBy = "Seeder",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2025, 2, 12, 2, 51, 30, 757, DateTimeKind.Local).AddTicks(784),
                            DateUpdated = new DateTime(2025, 2, 12, 2, 51, 30, 757, DateTimeKind.Local).AddTicks(789),
                            Duration = new TimeSpan(0, 0, 8, 25, 182),
                            FilePath = "/music/Hiroyuki Sawano Impure King Suite Epic Battle Music.mp3",
                            GenID = 1,
                            Id = 0,
                            LikedS = "NotLiked",
                            Name = "Hiroyuki Sawano Impure King Suite Epic Battle Music",
                            UpdateBy = "Seeder"
                        },
                        new
                        {
                            SongId = 16,
                            ArtistId = 1,
                            CreatedBy = "Seeder",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2025, 2, 12, 2, 51, 30, 757, DateTimeKind.Local).AddTicks(7317),
                            DateUpdated = new DateTime(2025, 2, 12, 2, 51, 30, 757, DateTimeKind.Local).AddTicks(7325),
                            Duration = new TimeSpan(1010207500),
                            FilePath = "/music/HOPE.mp3",
                            GenID = 1,
                            Id = 0,
                            LikedS = "NotLiked",
                            Name = "HOPE",
                            UpdateBy = "Seeder"
                        },
                        new
                        {
                            SongId = 17,
                            ArtistId = 1,
                            CreatedBy = "Seeder",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2025, 2, 12, 2, 51, 30, 758, DateTimeKind.Local).AddTicks(4475),
                            DateUpdated = new DateTime(2025, 2, 12, 2, 51, 30, 758, DateTimeKind.Local).AddTicks(4481),
                            Duration = new TimeSpan(2029805000),
                            FilePath = "/music/HOTD - Pentakill .mp3",
                            GenID = 1,
                            Id = 0,
                            LikedS = "NotLiked",
                            Name = "HOTD - Pentakill ",
                            UpdateBy = "Seeder"
                        },
                        new
                        {
                            SongId = 18,
                            ArtistId = 1,
                            CreatedBy = "Seeder",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2025, 2, 12, 2, 51, 30, 758, DateTimeKind.Local).AddTicks(9846),
                            DateUpdated = new DateTime(2025, 2, 12, 2, 51, 30, 758, DateTimeKind.Local).AddTicks(9852),
                            Duration = new TimeSpan(1892867500),
                            FilePath = "/music/i feel like i did too much Don Toliver - No Idea (Lyrics).mp3",
                            GenID = 1,
                            Id = 0,
                            LikedS = "NotLiked",
                            Name = "i feel like i did too much Don Toliver - No Idea (Lyrics)",
                            UpdateBy = "Seeder"
                        });
                });

            modelBuilder.Entity("Pancake_Final.Domain.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubId")
                        .HasColumnType("int");

                    b.Property<string>("SubPlans")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubStatus")
                        .HasColumnType("int");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Subscription");
                });

            modelBuilder.Entity("Pancake_Final.Domain.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayListID")
                        .HasColumnType("int");

                    b.Property<int>("SubId")
                        .HasColumnType("int");

                    b.Property<string>("SubStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Pancake_Final.Data.Pancake_FinalUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Pancake_Final.Data.Pancake_FinalUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pancake_Final.Data.Pancake_FinalUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Pancake_Final.Data.Pancake_FinalUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pancake_Final.Domain.Playlist", b =>
                {
                    b.HasOne("Pancake_Final.Domain.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Pancake_Final.Domain.Song", b =>
                {
                    b.HasOne("Pancake_Final.Domain.Artists", null)
                        .WithMany("Songs")
                        .HasForeignKey("ArtistsArtistID");

                    b.HasOne("Pancake_Final.Domain.Playlist", "Playlist")
                        .WithMany("Songs")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("Pancake_Final.Domain.Artists", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("Pancake_Final.Domain.Playlist", b =>
                {
                    b.Navigation("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
